import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Main from "../components/main";
import About from "../components/about";
import Skills from "../components/skills";
import Navbar from "../components/navbar";
import Projects from "../components/projects";
import Contact from "../components/contact";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Munniza | Frontend Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
      <About />
      <Skills />
      <Projects />
      <Contact />
    </>
  );
}
